{
	"id": "CVE-2023-39661",
	"tags": [
		{
			"label": "Product",
			"message": "n/a"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "n/a"
		}
	],
	"description": " An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.",
	"poc": {
		"references": [
			"https://github.com/gventuri/pandas-ai/issues/410"
		]
	}
}
