{
  "id": "CVE-2016-9949",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " An issue was discovered in Apport before 2.20.4. In apport/ui.py, Apport reads the CrashDB field and it then evaluates the field as Python code if it begins with a \"{\". This allows remote attackers to execute arbitrary Python code.",
  "poc": {
    "references": [
      "https://bugs.launchpad.net/apport/+bug/1648806",
      "https://github.com/DonnchaC/ubuntu-apport-exploitation",
      "https://www.exploit-db.com/exploits/40937/"
    ],
    "githubs": [
      "https://github.com/DonnchaC/ubuntu-apport-exploitation"
    ]
  }
}
