{
	"id": "CVE-2020-3878",
	"tags": [
		{
			"label": "Product",
			"message": "iCloud for Windows (Legacy)"
		},
		{
			"label": "Product",
			"message": "iCloud for Windows"
		},
		{
			"label": "Product",
			"message": "iOS"
		},
		{
			"label": "Product",
			"message": "iTunes for Windows"
		},
		{
			"label": "Product",
			"message": "macOS"
		},
		{
			"label": "Product",
			"message": "tvOS"
		},
		{
			"label": "Product",
			"message": "watchOS"
		},
		{
			"label": "Version",
			"message": "< iCloud for Windows 11.2 "
		},
		{
			"label": "Version",
			"message": "< iCloud for Windows 7.19 "
		},
		{
			"label": "Version",
			"message": "< iOS 13.5 and iPadOS 13.5 "
		},
		{
			"label": "Version",
			"message": "< iTunes 12.10.7 for Windows "
		},
		{
			"label": "Version",
			"message": "< macOS Catalina 10.15.5 "
		},
		{
			"label": "Version",
			"message": "< tvOS 13.4.5 "
		},
		{
			"label": "Version",
			"message": "< watchOS 6.2.5 "
		},
		{
			"label": "Vulnerability",
			"message": "Processing a maliciously crafted image may lead to arbitrary code execution"
		}
	],
	"description": " An out-of-bounds read was addressed with improved input validation. This issue is fixed in iOS 13.5 and iPadOS 13.5, macOS Catalina 10.15.5, tvOS 13.4.5, watchOS 6.2.5, iTunes 12.10.7 for Windows, iCloud for Windows 11.2, iCloud for Windows 7.19. Processing a maliciously crafted image may lead to arbitrary code execution.",
	"poc": {
		"githubs": [
			"https://github.com/ARPSyndicate/cvemon"
		]
	}
}
