{
  "id": "CVE-2020-15801",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
  "poc": {
    "githubs": [
      "https://github.com/ARPSyndicate/cvemon",
      "https://github.com/CoolerVoid/master_librarian"
    ]
  }
}
