{
  "id": "CVE-2020-24584",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.",
  "poc": {
    "references": [
      "https://www.oracle.com/security-alerts/cpujan2021.html"
    ],
    "githubs": [
      "https://github.com/404notf0und/CVE-Flow",
      "https://github.com/Live-Hack-CVE/CVE-2020-24584"
    ]
  }
}
