{
	"id": "CVE-2020-3826",
	"tags": [
		{
			"label": "Product",
			"message": "iCloud for Windows (Legacy)"
		},
		{
			"label": "Product",
			"message": "iCloud for Windows"
		},
		{
			"label": "Product",
			"message": "iOS"
		},
		{
			"label": "Product",
			"message": "iTunes for Windows"
		},
		{
			"label": "Product",
			"message": "macOS"
		},
		{
			"label": "Product",
			"message": "tvOS"
		},
		{
			"label": "Product",
			"message": "watchOS"
		},
		{
			"label": "Version",
			"message": "< iCloud for Windows 11.0 "
		},
		{
			"label": "Version",
			"message": "< iCloud for Windows 7.17 "
		},
		{
			"label": "Version",
			"message": "< iOS 13.3.1 and iPadOS 13.3.1 "
		},
		{
			"label": "Version",
			"message": "< iTunes for Windows 12.10.4 "
		},
		{
			"label": "Version",
			"message": "< macOS Catalina 10.15.3 "
		},
		{
			"label": "Version",
			"message": "< tvOS 13.3.1 "
		},
		{
			"label": "Version",
			"message": "< watchOS 6.1.2 "
		},
		{
			"label": "Vulnerability",
			"message": "Processing a maliciously crafted image may lead to arbitrary code execution"
		}
	],
	"description": " An out-of-bounds read was addressed with improved input validation. This issue is fixed in iOS 13.3.1 and iPadOS 13.3.1, macOS Catalina 10.15.3, tvOS 13.3.1, watchOS 6.1.2, iTunes for Windows 12.10.4, iCloud for Windows 11.0, iCloud for Windows 7.17. Processing a maliciously crafted image may lead to arbitrary code execution.",
	"poc": {
		"githubs": [
			"https://github.com/ARPSyndicate/cvemon"
		]
	}
}
