{
  "id": "CVE-2020-24583",
  "tags": [
    {
      "label": "Product",
      "message": "n/a"
    },
    {
      "label": "Version",
      "message": "n/a"
    },
    {
      "label": "Vulnerability",
      "message": "n/a"
    }
  ],
  "description": " An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
  "poc": {
    "references": [
      "https://www.oracle.com/security-alerts/cpujan2021.html"
    ],
    "githubs": [
      "https://github.com/404notf0und/CVE-Flow",
      "https://github.com/ARPSyndicate/cvemon",
      "https://github.com/Live-Hack-CVE/CVE-2020-24583"
    ]
  }
}
