{
	"id": "CVE-2021-20275",
	"tags": [
		{
			"label": "Product",
			"message": "privoxy"
		},
		{
			"label": "Version",
			"message": "n/a"
		},
		{
			"label": "Vulnerability",
			"message": "CWE-119"
		}
	],
	"description": " A flaw was found in privoxy before 3.0.32. A invalid read of size two may occur in chunked_body_is_complete() leading to denial of service.",
	"poc": {
		"githubs": [
			"https://github.com/MegaManSec/privoxy"
		]
	}
}
